services:
  auth:
    build: ./auth
    container_name: auth
    volumes:
      - ./auth:/app
    ports:
      - 80:5000
    env_file:
      - ./envFiles/.db.env
      - ./envFiles/.env
      - ./envFiles/.rbmq.env
    depends_on:
      - db
      - jwt_service
      - rabbitmq
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  jwt_service:
    build:
      context: ./jwt_auth
      dockerfile: Dockerfile
    volumes:
      - ./jwt_auth:/app
    container_name: jwt
    env_file:
      - ./envFiles/.jwt.env

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    env_file:
      - ./envFiles/.rbmq.env
    ports:
      - 8080:15672

  formatter:
    restart: always
    build:
      context: ./formatter
      dockerfile: Dockerfile
    env_file:
      - ./envFiles/.formatter.env
    volumes:
      - ./formatter:/app
  

volumes:
  rabbitmq:
    

      