CREATE USER 'admin'@'%' IDENTIFIED BY 'admin123';

CREATE DATABASE IF NOT EXISTS auth;

USE auth;

GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';

CREATE TABLE users(
    id INT PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
)